server:
  port: 8000
spring:
  datasource:
    name: peafowl
    url: jdbc:mysql://localhost:3306/peafowl?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#      exclude:
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yqwoe.codegenerator.model
logging:
  level:
     com.yqwoe.codegenerator.dao : debug
     com.yqwoe.codegenerator : debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




